version: '3.8'

services:
  app:
    build: .
    image: antonkuzmn1/my-portfolio-backend
    container_name: my-portfolio-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: no
