version: '3.8'

services:
  nest-app:
    image: antonkuzmn1/my-portfolio-backend
    container_name: my-portfolio-backend
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: always
    command: ['npm', 'start:prod']
