version: '3.8'

services:
  app:
    build: .
    container_name: antonkuzmn1/my-portfolio-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
